[build]
  # Build from the client subfolder. Netlify will change into this base before running the command.
  base = "client"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
