[build]
  # Build from the client subfolder. Netlify will change into this base before running the command.
  base = "client"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[_headers]]
  for = "/*"
  [[_headers.values]]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; media-src 'self' data: blob:; connect-src 'self' https://ebooklibrary-tors.onrender.com;"
